### ISSUE TITLE
关于文章置顶Bug的一个可能有用的临时(?)解决办法

### ISSUE THREAD

**Issue by lijiakaijun** [Anillc/merry#2]
今天趁手解决这遗留的bug时找到了这篇文章

https://www.jianshu.com/p/be6d87272856

然后将index.ejs中的23~27行换成下面的

````js
if(a.top && b.top) { // 两篇文章top都有定义
        if(a.top == b.top) return b.date - a.date; // 若top值一样则按照文章日期降序排
        else return b.top - a.top; // 否则按照top值降序排
    }
    else if(a.top && !b.top) { // 以下是只有一篇文章top有定义，那么将有top的排在前面（这里用异或操作居然不行233）
        return -1;
    }
    else if(!a.top && b.top) {
        return 1;
    }
    else return b.date - a.date; // 都没定义按照文章日期降序排
});
````

然后竟然成功了草

本地开hexo s刷新了几次发现不会再像之前那样~~蹦蹦跳跳~~了

~~顺带一说，我这的文章top属性挺乱的，每篇文章要么false要么true甚至是没赋值~~

~~我鬼知道这个Bug的根本原因在哪~~

**Comment by Anillc** [comment]
已修复，bug 的原因估计是我 sort 的函数里传入的参数我只判断了第一个参数是否为置顶，不知道 v8 内部 sort 是如何实现的。现在加上了判断两个参数是不是都置顶以及同时置顶就按时间拍的功能。
