### ISSUE TITLE
footer 配色 以及 一个建议

### ISSUE THREAD

**Issue by CEllenvia** [Anillc/merry#3]
![圖片](https://user-images.githubusercontent.com/108454429/177003168-fb44f393-c84f-463a-b94c-98c970b0a84d.png)

~~这个配色挺好的，下次别用了，没块HDR屏幕都看不出来那种~~

以及页脚有没有可能识别端，

PC或者其他长大于宽的屏幕使用全页脚+左放置，移动端保持现状？

如上。

**Comment by Anillc** [comment]
啊，我没考虑过用暗色的用户，我把链接的颜色都换成黑色了。你开亮色的话应该看着是没问题的，这个我之后看看能不能处理下。

另外放在一行的话感觉不会好看？

![image](https://user-images.githubusercontent.com/23411248/177003520-02968890-2f24-423d-b8ce-12083fbd9a16.png)

![image](https://user-images.githubusercontent.com/23411248/177003548-9cacd707-9567-4c8d-ba2e-1a7e19035404.png)

**Comment by CEllenvia** [comment]
> 啊，我没考虑过用暗色的用户，我把链接的颜色都换成黑色了。你开亮色的话应该看着是没问题的，这个我之后看看能不能处理下。
> 
> 另外放在一行的话感觉不会好看？
> 
> ![image](https://user-images.githubusercontent.com/23411248/177003520-02968890-2f24-423d-b8ce-12083fbd9a16.png)
> 
> ![image](https://user-images.githubusercontent.com/23411248/177003548-9cacd707-9567-4c8d-ba2e-1a7e19035404.png)

  我 [简单处理了一下](https://github.com/Anillc/merry/pull/4) 。此处感谢 @lijiakaijun 的帮助。

至于这个全页脚的问题，我当时是看到暗模式下有一个长条，就设计的希望页脚所在的那个长条能够把下面全屏占满。如图。

![圖片](https://user-images.githubusercontent.com/108454429/177006632-458e7138-725e-4f02-89ed-5257e64444f1.png)

这个我在我的 fork 单独实现吧。

**Comment by Anillc** [comment]
感谢您的 issue 和 pr。

我又进行了一些修改，删去了一些不必要的 css，然后解决了一下暗色模式 title 看着很怪的问题，发了 1.1.10 版本，你可以试一下。
